//! Execution records for one-shot and captured-recurring jobs.
//!
//! State layout under $XDG_STATE_HOME/looper/runs/<run_id>/:
//!   meta — newline-separated `key=value` lines, written by `_exec`
//!   out  — captured stdout (kernel-direct write; not size-capped in v1)
//!   err  — captured stderr (same)
//!
//! Lazy creation: the run dir doesn't exist until `_exec` starts. A job
//! whose marker has `once=1` but no corresponding run dir is "pending";
//! that derivation lives in the runs CLI, not here.
//!
//! Format choice — key=value newline lines, not JSON — matches looper's
//! marker idiom (forward-compatible: unknown keys are ignored), keeps a
//! single style across the codebase, and avoids depending on std.json's
//! still-evolving 0.16 API for an internal storage format.

const std = @import("std");
const posix = @import("../posix.zig");
const c = posix.c;
const backup = @import("backup.zig");
const target_mod = @import("target.zig");

pub const RunStatus = enum { pending, running, done, failed };

pub const RunRecord = struct {
    run_id: []const u8,
    /// Looper job id this came from (e.g. "daily-backup"). For one-shots
    /// generated by `looper once`, mirrors the job's synthetic id.
    source_id: ?[]const u8 = null,
    /// Inner user command (pre-wrapper). `_exec` knows the real command
    /// from its own argv; recording it here lets `runs show` describe the
    /// run without re-reading the crontab (which may have been mutated).
    command: []const u8,
    /// Human label like "local" / "file:/path" / "host:user@host" — for
    /// listing display. Optional because not every code path that creates
    /// a record has a target in hand.
    target_label: ?[]const u8 = null,
    /// True when this record came from a one-shot job (marker.once=1).
    once: bool = false,
    /// Cron's target firing epoch. For one-shots, the exact minute the
    /// job was set for; for captured-recurring runs this is the minute
    /// cron fired this iteration.
    scheduled_for: ?i64 = null,
    /// When `_exec` began executing the child. Null until then.
    started_at: ?i64 = null,
    /// When `_exec` recorded the child's exit. Null while still running.
    finished_at: ?i64 = null,
    /// Child exit code. Signed because waitpid can return -1 for kills.
    /// Null until finished.
    exit_code: ?i32 = null,
    /// True if `_exec` killed the child for exceeding timeout_secs.
    timed_out: bool = false,
};

/// Lifecycle classification derived from which fields are set.
/// `_exec`'s write order (started_at first, then finished_at) makes this
/// monotonic even if a reader picks up a meta file mid-write.
pub fn statusOf(r: RunRecord) RunStatus {
    if (r.started_at == null) return .pending;
    if (r.finished_at == null) return .running;
    if (r.timed_out) return .failed;
    if (r.exit_code) |code| return if (code == 0) .done else .failed;
    return .failed;
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

pub fn runsDir(a: std.mem.Allocator) []const u8 {
    return std.fmt.allocPrint(a, "{s}/runs", .{backup.stateDir(a)}) catch ".";
}

pub fn runDir(a: std.mem.Allocator, run_id: []const u8) []const u8 {
    return std.fmt.allocPrint(a, "{s}/{s}", .{ runsDir(a), run_id }) catch ".";
}

pub fn metaPath(a: std.mem.Allocator, run_id: []const u8) []const u8 {
    return std.fmt.allocPrint(a, "{s}/meta", .{runDir(a, run_id)}) catch ".";
}

pub fn outPath(a: std.mem.Allocator, run_id: []const u8) []const u8 {
    return std.fmt.allocPrint(a, "{s}/out", .{runDir(a, run_id)}) catch ".";
}

pub fn errPath(a: std.mem.Allocator, run_id: []const u8) []const u8 {
    return std.fmt.allocPrint(a, "{s}/err", .{runDir(a, run_id)}) catch ".";
}

pub fn ensureRunDir(a: std.mem.Allocator, run_id: []const u8) []const u8 {
    const d = runDir(a, run_id);
    backup.mkdirP(a, d);
    return d;
}

// ---------------------------------------------------------------------------
// Meta read/write — `key=value` newline lines
// ---------------------------------------------------------------------------

fn appendBool(a: std.mem.Allocator, out: *std.ArrayList(u8), key: []const u8, v: bool) void {
    const s = std.fmt.allocPrint(a, "{s}={d}\n", .{ key, @as(u8, if (v) 1 else 0) }) catch return;
    out.appendSlice(a, s) catch {};
}

fn appendStr(a: std.mem.Allocator, out: *std.ArrayList(u8), key: []const u8, v: []const u8) void {
    // We don't escape newlines/equals in `v`. cron commands are
    // single-line by definition and the key=value parser splits on the
    // first `=` so values containing `=` round-trip cleanly.
    const s = std.fmt.allocPrint(a, "{s}={s}\n", .{ key, v }) catch return;
    out.appendSlice(a, s) catch {};
}

fn appendInt(a: std.mem.Allocator, out: *std.ArrayList(u8), key: []const u8, v: i64) void {
    const s = std.fmt.allocPrint(a, "{s}={d}\n", .{ key, v }) catch return;
    out.appendSlice(a, s) catch {};
}

/// Render a RunRecord to the on-disk byte form.
pub fn metaSerialize(a: std.mem.Allocator, r: RunRecord) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    appendStr(a, &out, "run_id", r.run_id);
    if (r.source_id) |sid| appendStr(a, &out, "source_id", sid);
    appendStr(a, &out, "command", r.command);
    if (r.target_label) |tl| appendStr(a, &out, "target_label", tl);
    appendBool(a, &out, "once", r.once);
    if (r.scheduled_for) |t| appendInt(a, &out, "scheduled_for", t);
    if (r.started_at) |t| appendInt(a, &out, "started_at", t);
    if (r.finished_at) |t| appendInt(a, &out, "finished_at", t);
    if (r.exit_code) |code| appendInt(a, &out, "exit_code", @as(i64, code));
    appendBool(a, &out, "timed_out", r.timed_out);
    return out.toOwnedSlice(a);
}

/// Atomic write: produce tmp + rename. Matches doBackup's pattern so a
/// kill mid-write leaves the destination either fully present or absent.
pub fn metaWrite(a: std.mem.Allocator, r: RunRecord) !void {
    const d = ensureRunDir(a, r.run_id);
    const final_path = try std.fmt.allocPrint(a, "{s}/meta", .{d});
    const tmp_path = try std.fmt.allocPrint(a, "{s}.tmp", .{final_path});
    const bytes = try metaSerialize(a, r);
    try target_mod.writeFileAll(a, tmp_path, bytes);
    const src = try a.dupeZ(u8, tmp_path);
    const dst = try a.dupeZ(u8, final_path);
    if (c.rename(src.ptr, dst.ptr) != 0) {
        _ = c.unlink(src.ptr);
        return error.RenameFailed;
    }
}

fn parseBool(s: []const u8) bool {
    return std.mem.eql(u8, s, "1");
}

/// Parse a meta byte stream into a RunRecord. Unknown keys are silently
/// ignored — this is the forward-compat contract for the on-disk format.
/// Required key: run_id. Required key: command. Everything else optional.
pub fn metaParse(a: std.mem.Allocator, text: []const u8) !RunRecord {
    var run_id: ?[]const u8 = null;
    var source_id: ?[]const u8 = null;
    var command: ?[]const u8 = null;
    var target_label: ?[]const u8 = null;
    var once = false;
    var scheduled_for: ?i64 = null;
    var started_at: ?i64 = null;
    var finished_at: ?i64 = null;
    var exit_code: ?i32 = null;
    var timed_out = false;

    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |line| {
        if (line.len == 0) continue;
        const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const k = line[0..eq];
        const v = line[eq + 1 ..];
        if (std.mem.eql(u8, k, "run_id")) run_id = try a.dupe(u8, v)
        else if (std.mem.eql(u8, k, "source_id")) source_id = try a.dupe(u8, v)
        else if (std.mem.eql(u8, k, "command")) command = try a.dupe(u8, v)
        else if (std.mem.eql(u8, k, "target_label")) target_label = try a.dupe(u8, v)
        else if (std.mem.eql(u8, k, "once")) once = parseBool(v)
        else if (std.mem.eql(u8, k, "scheduled_for")) scheduled_for = std.fmt.parseInt(i64, v, 10) catch null
        else if (std.mem.eql(u8, k, "started_at")) started_at = std.fmt.parseInt(i64, v, 10) catch null
        else if (std.mem.eql(u8, k, "finished_at")) finished_at = std.fmt.parseInt(i64, v, 10) catch null
        else if (std.mem.eql(u8, k, "exit_code")) exit_code = std.fmt.parseInt(i32, v, 10) catch null
        else if (std.mem.eql(u8, k, "timed_out")) timed_out = parseBool(v);
        // unknown keys: silently ignored (forward-compat)
    }

    return RunRecord{
        .run_id = run_id orelse return error.MetaMissingRunId,
        .source_id = source_id,
        .command = command orelse return error.MetaMissingCommand,
        .target_label = target_label,
        .once = once,
        .scheduled_for = scheduled_for,
        .started_at = started_at,
        .finished_at = finished_at,
        .exit_code = exit_code,
        .timed_out = timed_out,
    };
}

/// Read a single run's meta file. Returns null if the file doesn't exist
/// or is empty — `target_mod.readFileAll` silently returns "" for missing
/// files, so empty-bytes is the "not found" signal here. Callers query by
/// arbitrary run_id and "not found" is normal.
pub fn metaRead(a: std.mem.Allocator, run_id: []const u8) !?RunRecord {
    const path = metaPath(a, run_id);
    const bytes = try target_mod.readFileAll(a, path);
    if (bytes.len == 0) return null;
    return try metaParse(a, bytes);
}

// ---------------------------------------------------------------------------
// Listing + pruning
// ---------------------------------------------------------------------------

/// Enumerate every run record under $state_dir/runs/. Skips entries that
/// don't have a readable meta file (in-progress dir creation, manual
/// junk, etc.) rather than erroring — matches backup.listBackups behavior.
pub fn listRuns(a: std.mem.Allocator) ![]RunRecord {
    const dir = runsDir(a);
    const dz = try a.dupeZ(u8, dir);
    const d = c.opendir(dz.ptr) orelse return &[_]RunRecord{};
    defer _ = c.closedir(d);
    var list: std.ArrayList(RunRecord) = .empty;
    while (true) {
        std.c._errno().* = 0;
        const ent = c.readdir(d) orelse break;
        const name = std.mem.span(@as([*:0]const u8, @ptrCast(&ent.*.d_name)));
        if (std.mem.eql(u8, name, ".") or std.mem.eql(u8, name, "..")) continue;
        const rec = (try metaRead(a, name)) orelse continue;
        try list.append(a, rec);
    }
    return list.toOwnedSlice(a);
}

pub const PruneResult = struct {
    kept: usize,
    removed: []const []const u8, // run_ids that were unlinked
};

/// Remove run dirs older than `older_than_secs` from now. `dry_run` lists
/// what would go without touching the filesystem. Records still in
/// "running" status (started but not finished) are never pruned — they
/// might just be slow.
pub fn pruneRuns(a: std.mem.Allocator, older_than_secs: i64, dry_run: bool) !PruneResult {
    const now = posix.nowEpoch();
    const cutoff = now - older_than_secs;
    const all = try listRuns(a);
    var removed: std.ArrayList([]const u8) = .empty;
    var kept_count: usize = 0;
    for (all) |r| {
        // Use finished_at if present, else scheduled_for, else started_at.
        // A record with none of these isn't prune-able — skip.
        const ts = r.finished_at orelse r.scheduled_for orelse r.started_at orelse {
            kept_count += 1;
            continue;
        };
        const running = r.started_at != null and r.finished_at == null;
        if (running or ts >= cutoff) {
            kept_count += 1;
            continue;
        }
        if (!dry_run) {
            removeRunDir(a, r.run_id);
        }
        try removed.append(a, r.run_id);
    }
    return .{
        .kept = kept_count,
        .removed = try removed.toOwnedSlice(a),
    };
}

fn removeRunDir(a: std.mem.Allocator, run_id: []const u8) void {
    // Best-effort recursive unlink of <runDir>/{meta,out,err} then rmdir.
    // We don't recurse arbitrarily — the layout is known and fixed.
    const d = runDir(a, run_id);
    for ([_][]const u8{ "meta", "out", "err" }) |fname| {
        const p = std.fmt.allocPrint(a, "{s}/{s}", .{ d, fname }) catch continue;
        const pz = a.dupeZ(u8, p) catch continue;
        _ = c.unlink(pz.ptr);
    }
    const dz = a.dupeZ(u8, d) catch return;
    _ = c.rmdir(dz.ptr);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

test "statusOf classifies all four lifecycle states" {
    try testing.expectEqual(RunStatus.pending, statusOf(.{ .run_id = "x", .command = "c" }));
    try testing.expectEqual(RunStatus.running, statusOf(.{ .run_id = "x", .command = "c", .started_at = 100 }));
    try testing.expectEqual(RunStatus.done, statusOf(.{ .run_id = "x", .command = "c", .started_at = 100, .finished_at = 200, .exit_code = 0 }));
    try testing.expectEqual(RunStatus.failed, statusOf(.{ .run_id = "x", .command = "c", .started_at = 100, .finished_at = 200, .exit_code = 1 }));
    try testing.expectEqual(RunStatus.failed, statusOf(.{ .run_id = "x", .command = "c", .started_at = 100, .finished_at = 200, .timed_out = true }));
}

test "metaSerialize emits canonical key=value lines" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const r = RunRecord{
        .run_id = "abc123",
        .source_id = "daily-backup",
        .command = "/bin/echo hi",
        .target_label = "local",
        .once = true,
        .scheduled_for = 1748016000,
        .started_at = 1748016001,
        .finished_at = 1748016003,
        .exit_code = 0,
    };
    const bytes = try metaSerialize(a, r);
    try testing.expect(std.mem.indexOf(u8, bytes, "run_id=abc123\n") != null);
    try testing.expect(std.mem.indexOf(u8, bytes, "source_id=daily-backup\n") != null);
    try testing.expect(std.mem.indexOf(u8, bytes, "command=/bin/echo hi\n") != null);
    try testing.expect(std.mem.indexOf(u8, bytes, "once=1\n") != null);
    try testing.expect(std.mem.indexOf(u8, bytes, "exit_code=0\n") != null);
    try testing.expect(std.mem.indexOf(u8, bytes, "timed_out=0\n") != null);
}

test "metaSerialize + metaParse round-trip" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const original = RunRecord{
        .run_id = "round-trip-test",
        .source_id = "src-1",
        .command = "/usr/bin/env DEMO=x /bin/echo hi",
        .target_label = "file:/tmp/x.crontab",
        .once = true,
        .scheduled_for = 1748016000,
        .started_at = 1748016001,
        .finished_at = 1748016003,
        .exit_code = 0,
        .timed_out = false,
    };
    const bytes = try metaSerialize(a, original);
    const parsed = try metaParse(a, bytes);
    try testing.expectEqualStrings(original.run_id, parsed.run_id);
    try testing.expectEqualStrings(original.source_id.?, parsed.source_id.?);
    try testing.expectEqualStrings(original.command, parsed.command);
    try testing.expectEqualStrings(original.target_label.?, parsed.target_label.?);
    try testing.expectEqual(original.once, parsed.once);
    try testing.expectEqual(original.scheduled_for.?, parsed.scheduled_for.?);
    try testing.expectEqual(original.started_at.?, parsed.started_at.?);
    try testing.expectEqual(original.finished_at.?, parsed.finished_at.?);
    try testing.expectEqual(original.exit_code.?, parsed.exit_code.?);
    try testing.expectEqual(original.timed_out, parsed.timed_out);
}

test "metaParse ignores unknown keys (forward-compat)" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const text =
        \\run_id=fwd-compat
        \\command=/bin/true
        \\future_field=42
        \\nested_thing=hello world
        \\once=1
        \\
    ;
    const r = try metaParse(a, text);
    try testing.expectEqualStrings("fwd-compat", r.run_id);
    try testing.expectEqualStrings("/bin/true", r.command);
    try testing.expect(r.once);
}

test "metaParse handles values containing equals signs" {
    // Cron commands frequently include env-var assignments like
    // FOO=bar before the command. Split-on-first-= must preserve those.
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const text =
        \\run_id=env-cmd
        \\command=PATH=/usr/local/bin /bin/echo hi
        \\
    ;
    const r = try metaParse(a, text);
    try testing.expectEqualStrings("PATH=/usr/local/bin /bin/echo hi", r.command);
}

test "metaParse rejects missing run_id" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const text = "command=/bin/true\n";
    try testing.expectError(error.MetaMissingRunId, metaParse(a, text));
}

test "metaParse rejects missing command" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const text = "run_id=x\n";
    try testing.expectError(error.MetaMissingCommand, metaParse(a, text));
}

test "metaSerialize omits unset optional fields" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const r = RunRecord{ .run_id = "minimal", .command = "/bin/true" };
    const bytes = try metaSerialize(a, r);
    try testing.expect(std.mem.indexOf(u8, bytes, "source_id") == null);
    try testing.expect(std.mem.indexOf(u8, bytes, "target_label") == null);
    try testing.expect(std.mem.indexOf(u8, bytes, "scheduled_for") == null);
    try testing.expect(std.mem.indexOf(u8, bytes, "started_at") == null);
    try testing.expect(std.mem.indexOf(u8, bytes, "finished_at") == null);
    try testing.expect(std.mem.indexOf(u8, bytes, "exit_code") == null);
    // once and timed_out are always emitted (bool defaults are recorded)
    try testing.expect(std.mem.indexOf(u8, bytes, "once=0") != null);
    try testing.expect(std.mem.indexOf(u8, bytes, "timed_out=0") != null);
}

test "metaRead returns null for nonexistent run_id" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const r = try metaRead(a, "definitely-does-not-exist-xyz-12345");
    try testing.expectEqual(@as(?RunRecord, null), r);
}

test "metaWrite then metaRead round-trips through the filesystem" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const run_id = try std.fmt.allocPrint(a, "test-rw-{x}", .{posix.nowEpoch()});
    const original = RunRecord{
        .run_id = run_id,
        .command = "/bin/echo round-trip",
        .once = true,
        .scheduled_for = 1748016000,
        .started_at = 1748016001,
        .finished_at = 1748016002,
        .exit_code = 0,
    };
    try metaWrite(a, original);
    defer {
        // Cleanup: remove the run dir we created.
        removeRunDir(a, run_id);
    }
    const got = (try metaRead(a, run_id)).?;
    try testing.expectEqualStrings(original.run_id, got.run_id);
    try testing.expectEqualStrings(original.command, got.command);
    try testing.expectEqual(original.once, got.once);
    try testing.expectEqual(original.scheduled_for, got.scheduled_for);
    try testing.expectEqual(original.exit_code, got.exit_code);
}
